### ISSUE TITLE
404 error messages

### ISSUE THREAD

**Issue by haydermabood** [jrcryer/generator-mean#1]
Hi,

I am getting the following 404 messages when I try to access "http://localhost:3000/"
........................................................

Running "jshint:all" (jshint) task

> > 8 files lint free.

Running "concurrent:tasks" (concurrent) task
Running "watch" task
Running "nodemon:dev" (nodemon) task
Waiting...23 Oct 17:10:45 - [nodemon] v0.7.10
23 Oct 17:10:45 - [nodemon] to restart at any time, enter `rs`
23 Oct 17:10:45 - [nodemon] watching: D:\WebDev\MEANStackTest2\app
23 Oct 17:10:45 - [nodemon] watching: D:\WebDev\MEANStackTest2\config
23 Oct 17:10:45 - [nodemon] starting `node server.js`
23 Oct 17:10:45 - [nodemon] reading ignore list
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Express app started on port 3000

GET / 304 1204ms
GET /lib/bootstrap/docs/assets/css/bootstrap.css 404 336ms
GET /lib/bootstrap/docs/assets/css/bootstrap-responsive.css 404 189ms
GET /lib/jquery/jquery.js 404 465ms
GET /lib/bootstrap/docs/assets/js/bootstrap.js 404 741ms
GET /lib/angular/angular.js 404 626ms
GET /lib/angular-cookies/angular-cookies.js 404 634ms
GET /lib/angular-resource/angular-resource.js 404 530ms
GET /lib/angular-bootstrap/ui-bootstrap-tpls.js 404 672ms
GET /lib/angular-ui-utils/modules/route/route.js 404 195ms
GET /lib/angular-resource/angular-resource.js 404 144ms
GET /lib/angular-bootstrap/ui-bootstrap-tpls.js 404 99ms
GET /lib/angular-ui-utils/modules/route/route.js 404 111ms

**Comment by jrcryer** [comment]
Hi,

Can you verify the location of your bower components? Are they installed to `app/bower_components`?

Ta,

James

**Comment by haydermabood** [comment]
Yes, check the attached images, it contains snapshots of the directory structure created by "yo mean".

![jrcryer-generator-mean-1](https://f.cloud.github.com/assets/5641697/1392437/07f84f84-3c0b-11e3-872a-59dd8be1c1c9.png)

![jrcryer-generator-mean-2](https://f.cloud.github.com/assets/5641697/1392470/a0163cb8-3c0b-11e3-8c44-ea572ede3f90.png)

**Comment by jrcryer** [comment]
I had a conflicting .bowerrc file.  I've added one to the project now, so when running:

```
yo mean
```

The bower components will be installed and picked up by the express app.

Thanks for all the details you sent across!
