### ISSUE TITLE
mkdir and/or confirm create path?

### ISSUE THREAD

**Issue by afknapping** [jrcryer/generator-mean#10]
Maybe this is intended behavior (or Yeoman standard), but `yo mean` just generated into my projects folder :)

Would definitely be nice to confirm the path the files are actually written into as part of the setup.

**Comment by jrcryer** [comment]
Hi, thanks for raising the issue - this is Yeoman's standard behaviour.  Please see http://yeoman.io/gettingstarted.html

Hope you find the generator useful :)
