### ISSUE TITLE
generator-angular commands

### ISSUE THREAD

**Issue by connor11528** [jrcryer/generator-mean#12]
Can this generator use commands from generator-angular to make routes and whatnot?

```
Available generators:

angular (aka angular:app)
angular:controller
angular:directive
angular:filter
angular:route
angular:service
angular:provider
angular:factory
angular:value
angular:constant
angular:decorator
angular:view
```

https://github.com/yeoman/generator-angular

**Comment by educatedrisk** [comment]
I just installed generator-mean and from what I tested it cannot use commands like you have listed above.  
When I tried one of those commands it just started up the original script again.

Think someone needs to get in contact with jrcryer and see if he is working on it.

**Comment by jrcryer** [comment]
@jasonshark did you mean to close this?  Would appreciate PRs for any of the above? I'm guess we start small and add one at time as I'm pretty busy at the moment on other projects

**Comment by connor11528** [comment]
no my bad, will leave open
