### ISSUE TITLE
Can't find option for passport support. Is it not available ..?

### ISSUE THREAD

**Issue by ravisuhag** [jrcryer/generator-mean#5]

**Comment by jrcryer** [comment]
Hi, this is not available yet.  The plan is to integrate this as an option in the near future.  Do you need it urgently?

**Comment by ravisuhag** [comment]
kind of ..

**Comment by jrcryer** [comment]
Cool - I'll see if I can add support later today.

**Comment by ravisuhag** [comment]
awesome .. thanx
